networks:
  default:
    external:
      name: robokart
services:
  mongodb:
    image: mongodb:1.0
    container_name: mongodb

  redis:
    image: redis
    container_name: redis

  catalogue:
    image: catalogue:1.0 
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:1.0
    container_name: user
    depends_on:
      - redis
      - mongodb
  
  web:
    image: web:1.0
    container_name: web 
    ports:
      - "80:80"
    depends_on:
      - catalogue
