networks:
  default:
    external:
      name: robokart
volumes:
  - mongodb
  - mysql
  - rabbitmq
  - redis
services:
  mongodb:
    image: mongodb:1.0
    container_name: mongodb
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
  redis:
    image: redis
    container_name: redis
    volumes:
      - type: volume
        source: redis
        target: /data

  mysql:
    image: mysql:1.0 
    container_name: mysql
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq

  catalogue:
    image: catalogue:1.0 
    container_name: catalogue
    depends_on:
      - mongodb
  cart:
    image: cart:1.0 
    container_name: cart
    depends_on:
      - redis
      - catalogue
  user:
    image: user:1.0
    container_name: user
    depends_on:
      - redis
      - mongodb
  shipping:
    image: shipping:1.0 
    container_name: shipping
    depends_on:
      - mysql
  payment:
    image: payment:1.0
    container_name: payment
    depends_on:
      - rabbitmq
      - user
      - cart


  web:
    image: web:1.0
    container_name: web 
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
