FROM ngnix 
RUN rm -rf /usr/share/ngnix/html/index.html 
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf

ADD robokart.conf /etc/nginx/nginx.conf
ADD /static /usr/share/ngnix/html/